import type {
  LiveAgentDebateResult,
  LiveAnalystResult,
  LiveClaimCounterpointResult,
  LiveCounterNarrativeResult,
  LiveDocument,
  LiveFinalReportResult,
  LiveInvestigationPlan,
  LiveInvestigationWorkspace,
  LiveNarrativeFamilyResult,
  LiveReceiptsResult,
  LiveRetrievalResult,
  LiveSourceDiversityResult,
  LiveTimelineResult,
} from "../types/rhetoriq";

const DEFAULT_QUERY = "Where did the hidden energy tax narrative come from?";
const DEFAULT_INVESTIGATION_ID = "mock-hidden-energy-tax";
const NOW = "2026-06-21T09:30:00Z";

const plan: LiveInvestigationPlan = {
  query_text: DEFAULT_QUERY,
  topic: "Hidden energy tax",
  primary_question: DEFAULT_QUERY,
  canonical_phrase: "hidden energy tax",
  intent: "trace_origin_and_spread",
  entities: ["State Energy Committee", "Families for Fair Rates", "National Policy Wire"],
  subquestions: [
    "What is the earliest clearly sourced use in the mock corpus?",
    "How does the phrase move across source classes during the day?",
    "What rebuttal or corrective framing appears after spread?",
  ],
  rival_hypotheses: [
    {
      id: "mock_local_origin",
      hypothesis: "The framing first stabilizes in local commentary before broader pickup.",
      rationale: "The fixture set begins with a local blog anchor.",
    },
    {
      id: "mock_advocacy_standardization",
      hypothesis: "Advocacy messaging helps standardize the phrase before national pickup.",
      rationale: "Later advocacy wording is cleaner and more reusable.",
    },
  ],
  disconfirming_evidence_criteria: [
    "If an earlier sourced document appears, the local-blog origin claim must be softened.",
    "If later coverage is mostly syndicated, the spread claim should be downgraded.",
  ],
  must_have_source_classes: ["local_news", "blog", "community_post", "official", "advocacy"],
  retrieval_lanes: ["discovery", "corroboration", "contradiction", "provenance", "official", "community"],
  search_queries: [
    "hidden energy tax origin",
    "hidden energy tax rate package",
    "hidden energy tax narrative spread",
  ],
  semantic_queries: [
    "cost of living framing around utility rate package",
    "long term savings counter frame to energy tax claim",
  ],
  target_source_types: ["local_news", "blog", "community_post", "official", "advocacy"],
  requested_outputs: ["timeline", "counter_narratives", "narrative_family", "report"],
  stop_conditions: [
    {
      id: "mock_origin_anchor",
      description: "Earliest anchor identified in the observed fixture set.",
      required: true,
      status: "satisfied",
    },
    {
      id: "mock_counter_search",
      description: "Counter-frame search attempted.",
      required: true,
      status: "satisfied",
    },
  ],
  time_window: {
    start: "2026-06-03T00:00:00Z",
    end: "2026-06-03T23:59:59Z",
    label: "single_day_spike",
  },
  retrieval_mode: "broad",
  risk_notes: [
    "Do not infer coordination from phrase reuse alone.",
    "Separate documented source pickup from broader interpretation.",
  ],
  uncertainty_requirements: [
    "Mark weak early mentions as uncertain.",
    "Prefer first clearly sourced usage over unsourced reposts.",
  ],
};

const documents: LiveDocument[] = [
  {
    id: "doc_local_blog",
    source_id: "src_local_blog",
    source_name: "Local Energy Watch",
    source_type: "blog",
    url: "https://example.com/local-energy-watch",
    title: "Why residents are calling the latest rate package a hidden energy tax",
    author: "Dana Flores",
    published_at: "2026-06-03T09:14:00Z",
    collected_at: "2026-06-03T09:20:00Z",
    text: "The post frames the rate package as a hidden energy tax on working households and links to the filing.",
    snippet: "The latest rate package is being framed by critics as a hidden energy tax on monthly bills.",
    language: "en",
    content_type: "article",
    geographic_scope: "local",
    entities: ["utility filing", "residents"],
    phrases: ["hidden energy tax", "monthly bills"],
    claims: ["The phrase first appears in a sourced local blog post."],
    duplicate_of_doc_id: null,
    is_seeded_demo_data: true,
    metadata: null,
    source_profile: {
      institution_kind: "independent",
      content_form: "original_reporting",
      ideology: "unknown",
      classification_method: "heuristic",
      classification_confidence: "medium",
    },
  },
  {
    id: "doc_community",
    source_id: "src_community",
    source_name: "Northside Neighbors",
    source_type: "community_post",
    url: "https://example.com/northside-neighbors",
    title: "Watch out for this hidden energy tax story",
    author: null,
    published_at: "2026-06-03T09:48:00Z",
    collected_at: "2026-06-03T10:00:00Z",
    text: "A neighborhood forum post links the local blog and repeats the same phrase almost verbatim.",
    snippet: "This hidden energy tax story is exactly what people warned about in the filing debate.",
    language: "en",
    content_type: "forum_post",
    geographic_scope: "local",
    entities: ["residents"],
    phrases: ["hidden energy tax"],
    claims: ["The phrase moves into community spaces shortly after first appearance."],
    duplicate_of_doc_id: null,
    is_seeded_demo_data: true,
    metadata: null,
    source_profile: {
      institution_kind: "community",
      content_form: "community_post",
      ideology: "unknown",
      classification_method: "heuristic",
      classification_confidence: "medium",
    },
  },
  {
    id: "doc_local_news",
    source_id: "src_local_news",
    source_name: "River City Bulletin",
    source_type: "local_news",
    url: "https://example.com/river-city-bulletin",
    title: "Critics call rate package a hidden energy tax",
    author: "M. Green",
    published_at: "2026-06-03T11:36:00Z",
    collected_at: "2026-06-03T11:45:00Z",
    text: "Regional outlets adopt the phrase in headlines and summaries, widening reach.",
    snippet: "Critics are describing the proposal as a hidden energy tax on monthly household bills.",
    language: "en",
    content_type: "article",
    geographic_scope: "regional",
    entities: ["critics", "rate package"],
    phrases: ["hidden energy tax"],
    claims: ["Local news pickup broadens the narrative."],
    duplicate_of_doc_id: null,
    is_seeded_demo_data: true,
    metadata: null,
    source_profile: {
      institution_kind: "media",
      content_form: "original_reporting",
      ideology: "center",
      classification_method: "heuristic",
      classification_confidence: "medium",
    },
  },
  {
    id: "doc_advocacy",
    source_id: "src_advocacy",
    source_name: "Families for Fair Rates",
    source_type: "advocacy",
    url: "https://example.com/families-for-fair-rates",
    title: "Families deserve answers on the hidden energy tax",
    author: null,
    published_at: "2026-06-03T12:24:00Z",
    collected_at: "2026-06-03T12:29:00Z",
    text: "An advocacy group uses the phrase in a cleaner, more repeatable cost-of-living message.",
    snippet: "Families deserve answers before this hidden energy tax becomes the new normal on monthly bills.",
    language: "en",
    content_type: "statement",
    geographic_scope: "state",
    entities: ["Families for Fair Rates"],
    phrases: ["hidden energy tax", "monthly bills"],
    claims: ["Advocacy messaging standardizes the framing."],
    duplicate_of_doc_id: null,
    is_seeded_demo_data: true,
    metadata: null,
    source_profile: {
      institution_kind: "advocacy",
      content_form: "opinion",
      ideology: "unknown",
      classification_method: "heuristic",
      classification_confidence: "medium",
    },
  },
  {
    id: "doc_official",
    source_id: "src_official",
    source_name: "State Energy Committee",
    source_type: "official",
    url: "https://example.com/state-energy-committee",
    title: "Rate package oversight hearing",
    author: null,
    published_at: "2026-06-03T13:32:00Z",
    collected_at: "2026-06-03T13:40:00Z",
    text: "A committee exchange references concerns being described publicly as a hidden energy tax.",
    snippet: "Public comments have described the proposal as a hidden energy tax, and we need to address that concern directly.",
    language: "en",
    content_type: "transcript",
    geographic_scope: "state",
    entities: ["State Energy Committee"],
    phrases: ["hidden energy tax"],
    claims: ["The phrase enters official discussion spaces."],
    duplicate_of_doc_id: null,
    is_seeded_demo_data: true,
    metadata: null,
    source_profile: {
      institution_kind: "official",
      content_form: "transcript",
      ideology: "unknown",
      classification_method: "registry",
      classification_confidence: "high",
    },
  },
  {
    id: "doc_national",
    source_id: "src_national",
    source_name: "National Policy Wire",
    source_type: "national_news",
    url: "https://example.com/national-policy-wire",
    title: "Hidden energy tax phrase jumps from local fight to national politics",
    author: "A. Reed",
    published_at: "2026-06-03T14:18:00Z",
    collected_at: "2026-06-03T14:24:00Z",
    text: "A national roundup treats the phrase as recognizable shorthand for the dispute.",
    snippet: "What started as a local backlash is now circulating nationally as a hidden energy tax argument.",
    language: "en",
    content_type: "article",
    geographic_scope: "national",
    entities: ["National Policy Wire"],
    phrases: ["hidden energy tax"],
    claims: ["National pickup makes the phrase broadly legible."],
    duplicate_of_doc_id: null,
    is_seeded_demo_data: true,
    metadata: null,
    source_profile: {
      institution_kind: "media",
      content_form: "original_reporting",
      ideology: "center",
      classification_method: "heuristic",
      classification_confidence: "medium",
    },
  },
  {
    id: "doc_counter",
    source_id: "src_counter",
    source_name: "Clean Grid Coalition",
    source_type: "advocacy",
    url: "https://example.com/clean-grid-coalition",
    title: "Long-term savings should not be erased by a hidden tax label",
    author: null,
    published_at: "2026-06-03T14:44:00Z",
    collected_at: "2026-06-03T14:49:00Z",
    text: "The response argues that the hidden energy tax frame ignores future savings and grid upgrades.",
    snippet: "Calling this a hidden energy tax leaves out the long-term savings and reliability benefits.",
    language: "en",
    content_type: "statement",
    geographic_scope: "national",
    entities: ["Clean Grid Coalition"],
    phrases: ["hidden energy tax", "long-term savings"],
    claims: ["A clear counter-frame emerges after the main narrative spreads."],
    duplicate_of_doc_id: null,
    is_seeded_demo_data: true,
    metadata: null,
    source_profile: {
      institution_kind: "advocacy",
      content_form: "opinion",
      ideology: "unknown",
      classification_method: "heuristic",
      classification_confidence: "medium",
    },
  },
];

const retrieval: LiveRetrievalResult = {
  investigation_id: DEFAULT_INVESTIGATION_ID,
  plan_snapshot: plan,
  retrieved_document_ids: documents.map((document) => document.id),
  high_relevance_document_ids: [
    "doc_local_blog",
    "doc_local_news",
    "doc_national",
    "doc_counter",
  ],
  main_narrative_document_ids: [
    "doc_local_blog",
    "doc_community",
    "doc_local_news",
    "doc_advocacy",
    "doc_official",
    "doc_national",
  ],
  counter_narrative_candidate_ids: ["doc_counter"],
  context_document_ids: ["doc_official"],
  document_annotations: documents.map((document, index) => ({
    document_id: document.id,
    retrieval_lane:
      index === 0
        ? "provenance"
        : index === 1
          ? "community"
          : index === 4
            ? "official"
            : index === 6
              ? "contradiction"
              : "discovery",
    retrieval_query: "hidden energy tax origin",
    pass_number: 1,
    relevance_score: 0.72,
    contradiction_signal: document.id === "doc_counter" ? 0.88 : 0.14,
    source_uniqueness_score: 0.9,
    primary_source_likelihood: document.id === "doc_official" ? 0.9 : 0.46,
    date_confidence: "high",
    quality_band: document.id === "doc_official" ? "tier_a" : "tier_b",
    duplicate_cluster_id: null,
    upstream_origin_hint: null,
    provenance_hint: document.id === "doc_local_blog" ? "possible_early_commentary_source" : null,
    independence_penalty: 0,
  })),
  warnings: [
    "This is seeded frontend mock data for UI debugging only.",
    "Source chronology is deterministic and does not reflect a live backend run.",
  ],
  coverage_summary: {
    total_documents: documents.length,
    unique_sources: documents.length,
    source_type_distribution: {
      blog: 1,
      community_post: 1,
      local_news: 1,
      advocacy: 2,
      official: 1,
      national_news: 1,
    },
    lane_distribution: {
      discovery: 3,
      corroboration: 1,
      contradiction: 1,
      provenance: 1,
      official: 1,
      community: 1,
    },
    has_counter_narrative_candidates: true,
    has_timeline_coverage: true,
    has_official_source: true,
    exact_phrase_hits: 6,
    search_rounds_completed: 2,
  },
  evidence_coverage_confidence: "high",
  cached: true,
};

const sourceDiversity: LiveSourceDiversityResult = {
  investigation_id: DEFAULT_INVESTIGATION_ID,
  plan_snapshot: plan,
  total_documents: documents.length,
  classified_documents: documents.length,
  source_type_distribution: {
    blog: 1,
    community_post: 1,
    local_news: 1,
    advocacy: 2,
    official: 1,
    national_news: 1,
  },
  geographic_distribution: {
    local: 2,
    regional: 1,
    state: 2,
    national: 2,
  },
  institution_distribution: {
    media: 2,
    advocacy: 2,
    official: 1,
    community: 1,
    independent: 1,
  },
  content_form_distribution: {
    original_reporting: 3,
    community_post: 1,
    opinion: 2,
    transcript: 1,
  },
  ideology_distribution: {
    center: 2,
    unknown: 5,
  },
  findings: [
    {
      id: "finding_1",
      label: "Mixed source base",
      detail: "Coverage spans local reporting, advocacy messaging, official context, and community reposts.",
    },
    {
      id: "finding_2",
      label: "Narrative acceleration",
      detail: "The phrase reaches larger media after first stabilizing in local and advocacy channels.",
    },
  ],
  limitations: ["Distribution counts reflect mock fixtures rather than live classification output."],
  confidence_score: 0.82,
  confidence_label: "high",
  cached: true,
};

const timeline: LiveTimelineResult = {
  investigation_id: DEFAULT_INVESTIGATION_ID,
  plan_snapshot: plan,
  timeline_events: [
    {
      id: "event_first",
      document_id: "doc_local_blog",
      timestamp: "2026-06-03T09:14:00Z",
      source_name: "Local Energy Watch",
      source_type: "blog",
      title: "First clearly sourced phrasing",
      url: "https://example.com/local-energy-watch",
      snippet: "The latest rate package is being framed by critics as a hidden energy tax on monthly bills.",
      event_type: "first_observed",
      narrative_side: "main",
      importance_score: 0.9,
      explanation: "This is the earliest clearly sourced use in the mock corpus.",
    },
    {
      id: "event_community",
      document_id: "doc_community",
      timestamp: "2026-06-03T09:48:00Z",
      source_name: "Northside Neighbors",
      source_type: "community_post",
      title: "Community pickup",
      url: "https://example.com/northside-neighbors",
      snippet: "This hidden energy tax story is exactly what people warned about in the filing debate.",
      event_type: "broader_pickup",
      narrative_side: "main",
      importance_score: 0.63,
      explanation: "The phrasing begins spreading through reposts and community chatter.",
    },
    {
      id: "event_local_news",
      document_id: "doc_local_news",
      timestamp: "2026-06-03T11:36:00Z",
      source_name: "River City Bulletin",
      source_type: "local_news",
      title: "Regional newsroom adoption",
      url: "https://example.com/river-city-bulletin",
      snippet: "Critics are describing the proposal as a hidden energy tax on monthly household bills.",
      event_type: "broader_pickup",
      narrative_side: "main",
      importance_score: 0.72,
      explanation: "Local news makes the phrase more visible and portable.",
    },
    {
      id: "event_official",
      document_id: "doc_official",
      timestamp: "2026-06-03T13:32:00Z",
      source_name: "State Energy Committee",
      source_type: "official",
      title: "Official mention",
      url: "https://example.com/state-energy-committee",
      snippet: "Public comments have described the proposal as a hidden energy tax, and we need to address that concern directly.",
      event_type: "official_mention",
      narrative_side: "related",
      importance_score: 0.69,
      explanation: "Institutional visibility increases, though this is not proof of official adoption.",
    },
    {
      id: "event_national",
      document_id: "doc_national",
      timestamp: "2026-06-03T14:18:00Z",
      source_name: "National Policy Wire",
      source_type: "national_news",
      title: "National pickup",
      url: "https://example.com/national-policy-wire",
      snippet: "What started as a local backlash is now circulating nationally as a hidden energy tax argument.",
      event_type: "broader_pickup",
      narrative_side: "main",
      importance_score: 0.86,
      explanation: "The phrase becomes national shorthand for the dispute.",
    },
    {
      id: "event_counter",
      document_id: "doc_counter",
      timestamp: "2026-06-03T14:44:00Z",
      source_name: "Clean Grid Coalition",
      source_type: "advocacy",
      title: "Long-term savings counter-frame",
      url: "https://example.com/clean-grid-coalition",
      snippet: "Calling this a hidden energy tax leaves out the long-term savings and reliability benefits.",
      event_type: "counter_narrative_entry",
      narrative_side: "counter",
      importance_score: 0.61,
      explanation: "A competing frame appears once the main phrasing has already spread.",
    },
  ],
  first_observed_doc_id: "doc_local_blog",
  timeline_summary: "The mock timeline shows a sourced local origin, fast community and newsroom pickup, then a national shorthand phase followed by a visible counter-frame.",
  limitations: ["Timeline order is fixed fixture data for frontend debugging."],
  confidence_score: 0.84,
  confidence_label: "high",
  cached: true,
};

const counterNarratives: LiveCounterNarrativeResult = {
  investigation_id: DEFAULT_INVESTIGATION_ID,
  plan_snapshot: plan,
  counter_narratives: [
    {
      id: "counter_long_term_savings",
      title: "Long-term savings response",
      summary: "Counter-messaging argues that the near-term cost frame omits future savings and grid reliability benefits.",
      canonical_phrase: "long-term savings",
      related_phrases: ["future savings", "grid reliability"],
      supporting_document_ids: ["doc_counter"],
      first_observed_doc_id: "doc_counter",
      relationship_to_main_narrative: "Directly disputes the cost-of-living emphasis in the main narrative.",
      confidence_score: 0.7,
    },
  ],
  notes: ["Counter-frame appears after the main phrase is already well established."],
  limitations: ["Only one counter-branch is included in the mock workspace."],
  confidence_score: 0.7,
  confidence_label: "medium",
  cached: true,
};

const narrativeFamily: LiveNarrativeFamilyResult = {
  investigation_id: DEFAULT_INVESTIGATION_ID,
  plan_snapshot: plan,
  family_title: "Hidden Energy Tax Narrative Family",
  parent_frame: "Utility costs are being reframed as an unfair household tax.",
  summary: "The main branch evolves from local complaint language into broader political shorthand, while one counter-branch pushes long-term savings and reliability.",
  child_narratives: [
    {
      id: "branch_local_origin",
      title: "Local cost complaint",
      canonical_phrase: "hidden energy tax",
      branch_type: "main",
      related_phrases: ["monthly bills", "rate package"],
      first_observed_doc_id: "doc_local_blog",
      relationship_to_parent: "Earliest sourced branch in the observed set.",
      growth_status: "emerging",
      branch_summary: "The phrase appears in local coverage tied directly to the filing.",
      supporting_document_ids: ["doc_local_blog", "doc_community"],
      source_count: 2,
      source_type_count: 2,
      source_diversity_score: 0.48,
      growth_score: 0.54,
    },
    {
      id: "branch_national_shorthand",
      title: "National shorthand",
      canonical_phrase: "hidden energy tax",
      branch_type: "mutation",
      related_phrases: ["cost backlash", "national politics"],
      first_observed_doc_id: "doc_national",
      relationship_to_parent: "Keeps the phrase but broadens the frame into national politics.",
      growth_status: "mainstreaming",
      branch_summary: "National media treats the phrase as already legible to a wider audience.",
      supporting_document_ids: ["doc_local_news", "doc_advocacy", "doc_official", "doc_national"],
      source_count: 4,
      source_type_count: 4,
      source_diversity_score: 0.81,
      growth_score: 0.89,
    },
    {
      id: "branch_counter_savings",
      title: "Long-term savings rebuttal",
      canonical_phrase: "long-term savings",
      branch_type: "counter",
      related_phrases: ["reliability benefits", "future savings"],
      first_observed_doc_id: "doc_counter",
      relationship_to_parent: "Counters the cost framing rather than adopting it.",
      growth_status: "emerging",
      branch_summary: "This branch argues the main narrative leaves out downstream benefits.",
      supporting_document_ids: ["doc_counter"],
      source_count: 1,
      source_type_count: 1,
      source_diversity_score: 0.36,
      growth_score: 0.44,
    },
  ],
  active_branch_id: "branch_national_shorthand",
  fastest_growing_child: "branch_national_shorthand",
  broadest_source_diversity_child: "branch_national_shorthand",
  mutation_summary: "The phrase remains stable, but the frame mutates from local billing criticism into reusable national political shorthand.",
  mutation_trail: [
    {
      from_phrase: "hidden energy tax on monthly bills",
      to_phrase: "hidden energy tax argument",
      from_doc_id: "doc_local_blog",
      to_doc_id: "doc_national",
      mutation_type: "mutation",
      similarity_score: 0.86,
      time_delta_hours: 5.1,
      source_shift: true,
      explanation: "The core phrase survives while the framing becomes broader and more reusable.",
    },
  ],
  limitations: ["Narrative family branches are intentionally small and deterministic in mock mode."],
  confidence_score: 0.78,
  confidence_label: "medium",
  generation_method: "deterministic",
  cached: true,
};

const analyst: LiveAnalystResult = {
  investigation_id: DEFAULT_INVESTIGATION_ID,
  plan_snapshot: plan,
  draft_report_sections: {
    executive_summary: "The mock evidence suggests the phrase begins in a clearly sourced local post, amplifies through community and newsroom reuse, and later becomes national shorthand.",
    observed_facts: "The dataset contains a sourced local origin, visible reposting, newsroom pickup, official mention, and a distinct counter-frame.",
    reasonable_inferences: "The spread pattern is consistent with rapid amplification, but not enough to claim coordinated intent.",
    timeline_summary: "Pickup accelerates after the first local post and becomes broader after newsroom and advocacy reuse.",
    counter_narrative_summary: "A long-term savings rebuttal emerges after the main frame is already circulating.",
    uncertainties: "The mock set is intentionally small and does not model missing-source gaps.",
  },
  candidate_claims: [
    {
      id: "claim_origin",
      claim_text: "The earliest clearly sourced use in the mock corpus is a local blog post.",
      claim_type: "origin",
      supporting_document_ids: ["doc_local_blog"],
      supporting_evidence_span_ids: ["event_first"],
      confidence_score: 0.9,
      caveats: ["Unsourced earlier mentions are excluded from the origin claim."],
    },
    {
      id: "claim_spread",
      claim_text: "The phrase spreads from local spaces into regional and national coverage within hours.",
      claim_type: "spread",
      supporting_document_ids: ["doc_community", "doc_local_news", "doc_national"],
      supporting_evidence_span_ids: ["event_community", "event_local_news", "event_national"],
      confidence_score: 0.84,
      caveats: ["Spread is based on fixture timestamps, not live crawling."],
    },
  ],
  limitations: ["Analyst output is mock data intended for frontend debugging."],
  recommended_human_checks: [
    "Verify whether any earlier sourced outlet used equivalent wording before the local blog.",
    "Check whether national pickup relied directly on advocacy summaries or independent reporting.",
  ],
  confidence_score: 0.83,
  confidence_label: "high",
  cached: true,
};

const claimCounterpoints: LiveClaimCounterpointResult = {
  investigation_id: DEFAULT_INVESTIGATION_ID,
  plan_snapshot: plan,
  pairs: [
    {
      claim_id: "claim_spread",
      main_claim_text: "The phrase spreads rapidly into larger media spaces.",
      counter_claim_text: "The cost frame omits long-term savings and reliability benefits.",
      counter_type: "reframing",
      relationship_summary: "The counterpoint does not dispute spread; it reframes what the spread should mean.",
      supporting_document_ids: ["doc_local_news", "doc_national"],
      counter_document_ids: ["doc_counter"],
      main_receipts: [
        {
          document_id: "doc_national",
          source_name: "National Policy Wire",
          source_type: "national_news",
          title: "Hidden energy tax phrase jumps from local fight to national politics",
          url: "https://example.com/national-policy-wire",
          published_at: "2026-06-03T14:18:00Z",
          snippet: "What started as a local backlash is now circulating nationally as a hidden energy tax argument.",
          relevance_note: "Shows broader uptake of the main phrase.",
        },
      ],
      counter_receipts: [
        {
          document_id: "doc_counter",
          source_name: "Clean Grid Coalition",
          source_type: "advocacy",
          title: "Long-term savings should not be erased by a hidden tax label",
          url: "https://example.com/clean-grid-coalition",
          published_at: "2026-06-03T14:44:00Z",
          snippet: "Calling this a hidden energy tax leaves out the long-term savings and reliability benefits.",
          relevance_note: "Shows a competing interpretive frame.",
        },
      ],
      confidence_score: 0.73,
      caveats: ["This pair is illustrative and based on a single counter document."],
    },
  ],
  unmatched_claim_ids: ["claim_origin"],
  limitations: ["Only one mock claim-counterpoint pair is included."],
  confidence_score: 0.73,
  confidence_label: "medium",
  cached: true,
};

const receipts: LiveReceiptsResult = {
  investigation_id: DEFAULT_INVESTIGATION_ID,
  plan_snapshot: plan,
  claim_receipts: [
    {
      claim_id: "claim_origin",
      claim_text: "The earliest clearly sourced use in the mock corpus is a local blog post.",
      claim_side: "main",
      support_status: "supported",
      support_summary: "The local blog post provides the earliest sourced wording in the fixture set.",
      supporting_receipts: [
        {
          document_id: "doc_local_blog",
          source_name: "Local Energy Watch",
          source_type: "blog",
          title: "Why residents are calling the latest rate package a hidden energy tax",
          url: "https://example.com/local-energy-watch",
          published_at: "2026-06-03T09:14:00Z",
          snippet: "The latest rate package is being framed by critics as a hidden energy tax on monthly bills.",
          evidence_span: "The latest rate package is being framed by critics as a hidden energy tax on monthly bills.",
          support_reason: "Earliest clearly sourced use in the mock workspace.",
          matched_terms: ["hidden energy tax"],
          verification_status: "verified",
        },
      ],
      contradicting_receipts: [],
      missing_evidence_notes: [],
      verification_state: "verified",
      confidence_score: 0.9,
      caveats: ["Mock workspace omits deeper pre-history search."],
    },
    {
      claim_id: "claim_spread",
      claim_text: "The phrase spreads from local spaces into regional and national coverage within hours.",
      claim_side: "main",
      support_status: "supported",
      support_summary: "The fixture timestamps show local, regional, and national pickup in sequence.",
      supporting_receipts: [
        {
          document_id: "doc_local_news",
          source_name: "River City Bulletin",
          source_type: "local_news",
          title: "Critics call rate package a hidden energy tax",
          url: "https://example.com/river-city-bulletin",
          published_at: "2026-06-03T11:36:00Z",
          snippet: "Critics are describing the proposal as a hidden energy tax on monthly household bills.",
          evidence_span: "Critics are describing the proposal as a hidden energy tax on monthly household bills.",
          support_reason: "Shows newsroom adoption after local and community use.",
          matched_terms: ["hidden energy tax"],
          verification_status: "verified",
        },
        {
          document_id: "doc_national",
          source_name: "National Policy Wire",
          source_type: "national_news",
          title: "Hidden energy tax phrase jumps from local fight to national politics",
          url: "https://example.com/national-policy-wire",
          published_at: "2026-06-03T14:18:00Z",
          snippet: "What started as a local backlash is now circulating nationally as a hidden energy tax argument.",
          evidence_span: "What started as a local backlash is now circulating nationally as a hidden energy tax argument.",
          support_reason: "Shows later national visibility.",
          matched_terms: ["hidden energy tax"],
          verification_status: "verified",
        },
      ],
      contradicting_receipts: [],
      missing_evidence_notes: [],
      verification_state: "verified",
      confidence_score: 0.84,
      caveats: ["Speed of spread is limited to the mock fixture timeline."],
    },
  ],
  counter_claim_receipts: [
    {
      claim_id: "counter_savings",
      claim_text: "The phrase leaves out long-term savings and reliability benefits.",
      claim_side: "counter",
      support_status: "supported",
      support_summary: "The counter-frame is explicitly articulated in the advocacy response.",
      supporting_receipts: [
        {
          document_id: "doc_counter",
          source_name: "Clean Grid Coalition",
          source_type: "advocacy",
          title: "Long-term savings should not be erased by a hidden tax label",
          url: "https://example.com/clean-grid-coalition",
          published_at: "2026-06-03T14:44:00Z",
          snippet: "Calling this a hidden energy tax leaves out the long-term savings and reliability benefits.",
          evidence_span: "Calling this a hidden energy tax leaves out the long-term savings and reliability benefits.",
          support_reason: "Provides the clearest counter-frame in the mock set.",
          matched_terms: ["long-term savings"],
          verification_status: "verified",
        },
      ],
      contradicting_receipts: [],
      missing_evidence_notes: [],
      verification_state: "verified",
      confidence_score: 0.74,
      caveats: [],
    },
  ],
  limitations: ["Receipt verification statuses are prefilled in mock mode."],
  confidence_score: 0.85,
  confidence_label: "high",
  cached: true,
};

const agentDebate: LiveAgentDebateResult = {
  investigation_id: DEFAULT_INVESTIGATION_ID,
  plan_snapshot: plan,
  analyst_position: "The spread pattern is strong enough to describe a sourced local origin followed by rapid amplification.",
  skeptic_response: "Do not overclaim on coordination or claim the absolute first-ever usage beyond this fixture set.",
  receipts_check: "Core origin and spread claims are directly grounded in mock receipts.",
  counter_narrative_note: "A long-term savings rebuttal is visible, but it trails the main frame chronologically.",
  safety_grounding_decision: "Use cautious wording about spread and avoid intent claims.",
  final_language_decision: "Describe sourced origin, observed spread, and counter-frame emergence without asserting truth judgments.",
  rejected_claims: ["The phrase was definitively invented by a single actor."],
  softened_claims: [
    {
      claim_id: "claim_spread",
      original: "The phrase went viral nationwide in a coordinated push.",
      softened: "The phrase spread rapidly into regional and national coverage in the observed mock dataset.",
      reason: "Coordination is not evidenced by the fixture data.",
    },
  ],
  limitations: ["Debate output is static in frontend-only mode."],
  confidence_score: 0.8,
  confidence_label: "high",
  cached: true,
};

const report: LiveFinalReportResult = {
  investigation_id: DEFAULT_INVESTIGATION_ID,
  plan_snapshot: plan,
  report_title: "Hidden Energy Tax Investigation",
  report_summary: "In mock mode, the narrative begins in a sourced local post, amplifies through community and newsroom reuse, becomes national shorthand, and then attracts a visible counter-frame.",
  sections: {
    headline: "How the hidden energy tax phrase traveled",
    executive_summary: "The mock evidence shows a sourced local origin and rapid amplification across several source types.",
    observed_facts: "The fixture set includes local, community, newsroom, official, advocacy, and national documents.",
    reasonable_inferences: "The spread pattern suggests narrative acceleration, but not coordinated intent.",
    timeline_summary: "The phrase stabilizes locally before larger outlets adopt it later in the day.",
    counter_narrative_summary: "The main rebuttal argues the phrase ignores long-term savings and reliability.",
    limitations: "This report is generated from seeded frontend data, not a live backend run.",
    recommended_human_checks: "Verify earlier sourced usage and whether later outlets independently confirmed the underlying claim.",
  },
  key_claims: [
    {
      claim_id: "claim_origin",
      claim_text: "The earliest clearly sourced use in this frontend-only workspace is a local blog post.",
      claim_type: "origin",
      confidence_score: 0.9,
      caveats: ["This does not rule out earlier unsourced mentions."],
      citations: [
        {
          document_id: "doc_local_blog",
          source_name: "Local Energy Watch",
          source_type: "blog",
          title: "Why residents are calling the latest rate package a hidden energy tax",
          url: "https://example.com/local-energy-watch",
          published_at: "2026-06-03T09:14:00Z",
          snippet: "The latest rate package is being framed by critics as a hidden energy tax on monthly bills.",
          relevance_note: "Earliest sourced wording in the mock set.",
        },
      ],
      support_status: "supported",
      support_summary: "The local blog post is the first clearly sourced phrasing in the mock workspace.",
      supporting_receipts: receipts.claim_receipts[0].supporting_receipts,
      contradicting_receipts: [],
      missing_evidence_notes: [],
      verification_state: "verified",
      counterpoint_summary: null,
      counterpoint_type: null,
      counter_citations: [],
    },
    {
      claim_id: "claim_spread",
      claim_text: "The phrase spreads from local spaces into regional and national coverage within hours in the observed mock timeline.",
      claim_type: "spread",
      confidence_score: 0.84,
      caveats: ["Timing is based on seeded fixture timestamps."],
      citations: [
        {
          document_id: "doc_local_news",
          source_name: "River City Bulletin",
          source_type: "local_news",
          title: "Critics call rate package a hidden energy tax",
          url: "https://example.com/river-city-bulletin",
          published_at: "2026-06-03T11:36:00Z",
          snippet: "Critics are describing the proposal as a hidden energy tax on monthly household bills.",
          relevance_note: "Regional pickup point.",
        },
        {
          document_id: "doc_national",
          source_name: "National Policy Wire",
          source_type: "national_news",
          title: "Hidden energy tax phrase jumps from local fight to national politics",
          url: "https://example.com/national-policy-wire",
          published_at: "2026-06-03T14:18:00Z",
          snippet: "What started as a local backlash is now circulating nationally as a hidden energy tax argument.",
          relevance_note: "National pickup point.",
        },
      ],
      support_status: "supported",
      support_summary: "The fixture sequence shows pickup from community and local news into national coverage.",
      supporting_receipts: receipts.claim_receipts[1].supporting_receipts,
      contradicting_receipts: [],
      missing_evidence_notes: [],
      verification_state: "verified",
      counterpoint_summary: "A visible rebuttal argues the phrase obscures long-term savings and reliability benefits.",
      counterpoint_type: "reframing",
      counter_citations: claimCounterpoints.pairs[0].counter_receipts,
    },
    {
      claim_id: "claim_caution",
      claim_text: "The mock evidence supports describing spread, but not coordination or truth of the underlying policy claim.",
      claim_type: "assessment",
      confidence_score: 0.78,
      caveats: ["The workspace is for UI debugging and has limited fixture breadth."],
      citations: [
        {
          document_id: "doc_official",
          source_name: "State Energy Committee",
          source_type: "official",
          title: "Rate package oversight hearing",
          url: "https://example.com/state-energy-committee",
          published_at: "2026-06-03T13:32:00Z",
          snippet: "Public comments have described the proposal as a hidden energy tax, and we need to address that concern directly.",
          relevance_note: "Supports broader visibility without resolving the underlying policy truth.",
        },
      ],
      support_status: "partially_supported",
      support_summary: "The records show spread into visible institutions, but they do not establish intent or truth.",
      supporting_receipts: [
        {
          document_id: "doc_official",
          source_name: "State Energy Committee",
          source_type: "official",
          title: "Rate package oversight hearing",
          url: "https://example.com/state-energy-committee",
          published_at: "2026-06-03T13:32:00Z",
          snippet: "Public comments have described the proposal as a hidden energy tax, and we need to address that concern directly.",
          evidence_span: "Public comments have described the proposal as a hidden energy tax, and we need to address that concern directly.",
          support_reason: "Shows visibility of the phrase without validating the claim itself.",
          matched_terms: ["hidden energy tax"],
          verification_status: "verified",
        },
      ],
      contradicting_receipts: [],
      missing_evidence_notes: ["No evidence of coordinated planning is present in mock mode."],
      verification_state: "verified",
      counterpoint_summary: null,
      counterpoint_type: null,
      counter_citations: [],
    },
  ],
  evidence_packet: [
    {
      document_id: "doc_local_blog",
      source_name: "Local Energy Watch",
      source_type: "blog",
      title: "Why residents are calling the latest rate package a hidden energy tax",
      url: "https://example.com/local-energy-watch",
      published_at: "2026-06-03T09:14:00Z",
      snippet: "The latest rate package is being framed by critics as a hidden energy tax on monthly bills.",
      relevance_note: "Origin evidence.",
    },
    {
      document_id: "doc_national",
      source_name: "National Policy Wire",
      source_type: "national_news",
      title: "Hidden energy tax phrase jumps from local fight to national politics",
      url: "https://example.com/national-policy-wire",
      published_at: "2026-06-03T14:18:00Z",
      snippet: "What started as a local backlash is now circulating nationally as a hidden energy tax argument.",
      relevance_note: "Spread evidence.",
    },
    {
      document_id: "doc_counter",
      source_name: "Clean Grid Coalition",
      source_type: "advocacy",
      title: "Long-term savings should not be erased by a hidden tax label",
      url: "https://example.com/clean-grid-coalition",
      published_at: "2026-06-03T14:44:00Z",
      snippet: "Calling this a hidden energy tax leaves out the long-term savings and reliability benefits.",
      relevance_note: "Counter-frame evidence.",
    },
  ],
  limitations: [
    "This workspace is seeded frontend data for component and layout debugging.",
    "No live backend retrieval or agent execution occurs in mock mode.",
  ],
  recommended_human_checks: analyst.recommended_human_checks,
  confidence_score: 0.84,
  confidence_label: "high",
  confidence_dimensions: {
    coverage_confidence: { score: 0.84, reason: "Fixture set spans multiple source classes." },
    chronology_confidence: { score: 0.82, reason: "Mock timeline includes ordered dated events." },
    contradiction_confidence: { score: 0.7, reason: "One direct counter-frame is present in the fixtures." },
    provenance_confidence: { score: 0.68, reason: "Local blog is the earliest anchor in the mock corpus." },
    verification_confidence: { score: 0.86, reason: "Receipt verification is prefilled as verified in mock mode." },
    synthesis_confidence: { score: 0.84, reason: "The mock report preserves uncertainty around coordination and policy truth." },
  },
  cached: true,
};

export function isMockInvestigationRequest(
  investigationId: string,
  query: URLSearchParams,
) {
  return (
    investigationId.startsWith("mock-") ||
    query.get("mock") === "1" ||
    import.meta.env.VITE_FRONTEND_ONLY_INVESTIGATION === "1"
  );
}

export function getMockInvestigationWorkspace(
  investigationId = DEFAULT_INVESTIGATION_ID,
  queryText?: string,
): LiveInvestigationWorkspace {
  const nextQuery = queryText?.trim() || DEFAULT_QUERY;
  const nextPlan = {
    ...plan,
    query_text: nextQuery,
    topic: nextQuery.includes("?") ? "Frontend Mock Investigation" : plan.topic,
  };

  return {
    investigation_id: investigationId || DEFAULT_INVESTIGATION_ID,
    query_text: nextQuery,
    status: "report_completed",
    current_stage: "report",
    created_at: NOW,
    updated_at: NOW,
    plan: nextPlan,
    retrieval: {
      ...retrieval,
      investigation_id: investigationId || DEFAULT_INVESTIGATION_ID,
      plan_snapshot: nextPlan,
    },
    retrieved_documents: documents,
    source_diversity: {
      ...sourceDiversity,
      investigation_id: investigationId || DEFAULT_INVESTIGATION_ID,
      plan_snapshot: nextPlan,
    },
    timeline: {
      ...timeline,
      investigation_id: investigationId || DEFAULT_INVESTIGATION_ID,
      plan_snapshot: nextPlan,
    },
    counter_narratives: {
      ...counterNarratives,
      investigation_id: investigationId || DEFAULT_INVESTIGATION_ID,
      plan_snapshot: nextPlan,
    },
    narrative_family: {
      ...narrativeFamily,
      investigation_id: investigationId || DEFAULT_INVESTIGATION_ID,
      plan_snapshot: nextPlan,
    },
    gap_analysis: null,
    skeptic_review: null,
    claim_ledger: null,
    gap_ledger: null,
    provenance_trace: null,
    research_loop: null,
    analyst: {
      ...analyst,
      investigation_id: investigationId || DEFAULT_INVESTIGATION_ID,
      plan_snapshot: nextPlan,
    },
    claim_counterpoints: {
      ...claimCounterpoints,
      investigation_id: investigationId || DEFAULT_INVESTIGATION_ID,
      plan_snapshot: nextPlan,
    },
    receipts: {
      ...receipts,
      investigation_id: investigationId || DEFAULT_INVESTIGATION_ID,
      plan_snapshot: nextPlan,
    },
    agent_debate: {
      ...agentDebate,
      investigation_id: investigationId || DEFAULT_INVESTIGATION_ID,
      plan_snapshot: nextPlan,
    },
    report: {
      ...report,
      investigation_id: investigationId || DEFAULT_INVESTIGATION_ID,
      plan_snapshot: nextPlan,
    },
  };
}
